version: '3.9'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_DB: geo_api
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d geo_api"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB: geo_api
      USER: user
      PASSWORD: qwerty123

volumes:
  pgdata: